name: Check Pull Requests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    name: Tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn test

  prettier:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    name: Format code with Prettier
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn format:check

  eslint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    name: Lint code with eslint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn lint:check

  types:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    name: Check TypeScript types
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn types:check

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    name: Build the projects
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn build
